### PR TITLE
feat: failing download doesn't cause script to fail

### PR DESCRIPTION
**Pull request by WiktorG**
Hi there! :) 

I started using the package like before the weekend but for some reason it was failing when merging metadata. 

I even saw an issue on that. 
I created a small fix for this bug.

When the download fails I added a note to the terminal that tells that something went wrong during fail. It doesn't crash anymore. Just skips the download and jumps to another song.

I know this code isn't the cleanest but it fixes the bug :)

### CODE REVIEW

**Comment by SwapnilSoni1999** [comment]
Great help sir
Also please can you confirm with a song and playlist download test. Will be very helpful

**Comment by WiktorG** [comment]
This error didn't occure every time user downloads a playlist but it does sometimes. 
I don't know what's causing it because different times, different songs failed.

**We should check what's causing downloads to fail :D** 

Here is the playlist that failed randomly: 
https://open.spotify.com/playlist/1rPNGZ0mUBNrzIY9mgKhgW?si=7MYsq9ZbRD6x3Uifv9d-cg

**Comment by WiktorG** [comment]
You should try to download it a few times

**Comment by SwapnilSoni1999** [comment]
> You should try to download it a few times

Will surely check after covid recovery will take some time though

**Comment by WiktorG** [comment]
> > You should try to download it a few times
> 
> Will surely check after covid recovery will take some time though

Sure! I hope you'll get well soon. 
I'll take a look when I have time what's causing album downloads to fail :)

**Comment by WiktorG** [comment]
@SwapnilSoni1999 
I fixed some more things I caused to fail xD 
Everything seems to work fine right now. Even album download :)

**Comment by PrincessAkira** [comment]
Can confirm that it works, BUT i get a random Parsing Info error.

```
Downloading...Error: Input stream error: Error parsing info: Unable to retrieve video metadata
    at PassThrough.<anonymous> (C:\Users\Yukii\Desktop\New folder\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:452:34)
    at PassThrough.emit (events.js:315:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by WiktorG** [comment]
@PrincessAkira - Sure I'll look into that after work. I guess there needs to be added additional error handling somewhere in the loop. Thank you for the tip

**Comment by WiktorG** [comment]
Ok - found some time :) I bumped ytdl-core, added additional error handler and I couldn't replicate your error. Try now and let me know

**Comment by jgreaves8** [comment]
anything I can do to help with this?

**Comment by WiktorG** [comment]
@jgreaves8 - hi :) 

I didn't have much time lately. I will look into it during the weekend and ping you if there's anything I won't be able to fix during my free time :)

**Comment by ashmoser06** [comment]
> 
> 
> > You should try to download it a few times
> 
> Will surely check after covid recovery will take some time though

Get well soon, @SwapnilSoni1999

**Comment by SwapnilSoni1999** [comment]
> > > You should try to download it a few times
> > 
> > 
> > Will surely check after covid recovery will take some time though
> 
> Get well soon, @SwapnilSoni1999

Yes i got recovered but unfortunately my father couldn't survive this virus

**Comment by WiktorG** [comment]
> > > > You should try to download it a few times
> > > 
> > > 
> > > Will surely check after covid recovery will take some time though
> > 
> > 
> > Get well soon, @SwapnilSoni1999
> 
> Yes i got recovered but unfortunately my father couldn't survive this virus

Ohhhhh - I'm so sorry :(

**Comment by phyzical** [comment]
@WiktorG @PrincessAkira  if you can could you please confirm this is fixed in my pr https://github.com/SwapnilSoni1999/spotify-dl/pull/84 i tested the provided url in start of the issue and it seems to be resolved, the pr itself could use some testing from other users incase i've introduced any regressions i didnt notice 👍

**Comment by phyzical** [comment]
This should now be closable 👍

**Pull request closed without merging**
