### PR TITLE
Hotfix/fix when metadata image missing

### LINKED ISSUE #114: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
**Describe the bug**
Once a specific song is downloaded, it just throws a type error. The song in question doesn't have any metadata.

**To Reproduce**
1. create a new folder
2. get into it
3. run : spotifydl -o LND https://open.spotify.com/playlist/0aJyer4nHU7lPMHIJR5dTY

**Expected behavior**
Should download the full playlist.

**Screenshots**
not required

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04LTS
 - Browser : doesn't matter
 - Version : Doesn't matter

**Additional context**
Here is the full response : 

ℹ Downloading: LDN Classics - misssmokingkills
ℹ Total Songs: 136
ℹ 55/136
Artist: 
Album: 
Song: UYCD003 Douglas Greed feat Delhia de France - Sense (André Lodemann Remix)
✔ Download completed.
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:160:3)
    at Object.urlParse [as parse] (url.js:155:13)
    at dispatchHttpRequest (/usr/lib/node_modules/spotify-dl/node_modules/axios/lib/adapters/http.js:91:22)
    at new Promise (<anonymous>)
    at httpAdapter (/usr/lib/node_modules/spotify-dl/node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (/usr/lib/node_modules/spotify-dl/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async downloadAndSaveCover (/usr/lib/node_modules/spotify-dl/lib/metadata.js:9:17)

### PR DESCRIPTION
**Pull request by phyzical**
# Added fix for when metadata image isnt found to fallback to generic image

* now collects all metadata for all requested types then downloads them all at once
* also now outputs a download report to show any missed items for when no youtube urls or maybe the youtube dl fails
* small lock update
* slight change to allow downloads to continue when a youtube download fails rather than stoping whole list

## Checklist
[x] Ran eslint/prettier formatting
[x] Tests are passing (no tests yet)
[x] Feature is considered complete

## Issues this resolves
fixes #114

### CODE REVIEW

**Comment by phyzical** [comment]
@SwapnilSoni1999 note this is branched off of #115  please merge this before reviewing

**Comment by phyzical** [comment]
@SwapnilSoni1999 rebased for review 👍

**Comment by SwapnilSoni1999** [comment]
Should I merge this one first than other branches?

**Comment by phyzical** [comment]
@SwapnilSoni1999 merge this one and i can rebase the other one for you to review :)

**Comment by SwapnilSoni1999** [comment]
> @SwapnilSoni1999 merge this one and i can rebase the other one for you to review :)

Alrighty :)

**Pull request merged**
