### PR TITLE
Fix #171

### LINKED ISSUE #171: Covers of songs have `EOI missing` (according to ffprobe)
**Describe the bug**
Most of the covers of the songs have `EOI` missing (according to ffprobe), which means that the image is corrupt or didn't finish downloading when being added to the song. This leads to the image not displaying correctly on file managers, music players...

**To Reproduce**
1. Download any playlist with the spotify-dl cli and most images should be like this.

**Expected behavior**
Images fine added to the song.

**Screenshots**
image
image

**Desktop (please complete the following information):**
 - OS: Arch Linux (5.18.14-arch1-1)
 - Browser Firefox (Mozilla Firefox 103.0)
 - spotify-dl version: 1.0.8

### PR DESCRIPTION
**Pull request by javalsai**
# Title
Fix problem with song covers being corrupt.

## Details
Instead of just downloading the cover, it passes it though ffmpeg to ensure the format is jpg.

## Testing
Downloaded the same playlist of #171 and running ffprobe didn't return any problems, also no apparent problems in file managers.

## Checklist
[X] Ran eslint/prettier formatting
[ ] Tests are passing (no tests yet)
[X] Feature is considered complete

## Issues this resolves
fixes and closes #171

### CODE REVIEW

**Comment by phyzical** [comment]
there was also this pr i made to attempt to fix it, though its a more of "okay lets try again" might aswell chuck these changes in with yours if you want

https://github.com/SwapnilSoni1999/spotify-dl/pull/162

but not a big deal if you think the png 100% solves the problem we can just ditch this pr

**Comment by phyzical** [comment]
Oh there is one thing i remeber about using ffmpeg if the the image is corrupt the flow will be killed so i think there needs to be a catch from memory, you should be able to test it by hardcoding a bad image and passing that garbage straight into ffmpeg

**Comment by javalsai** [comment]
> there was also this pr i made to attempt to fix it, though its a more of "okay lets try again" might aswell chuck these changes in with yours if you want
> 
> #162
> 
> but not a big deal if you think the png 100% solves the problem we can just ditch this pr

Ohh, I see, I think that both PRs can work together, but because I'm very bad at this of git and I don't want to mess everything up trying to bring your PR to my fork, I'll wait until owner merges your PR and then work with it.


> Oh there is one thing i remeber about using ffmpeg if the the image is corrupt the flow will be killed so i think there needs to be a catch from memory, you should be able to test it by hardcoding a bad image and passing that garbage straight into ffmpeg

Yes, that's a good idea that I'll do when combining our PRs.

**Comment by javalsai** [comment]
Should I convert this PR to a draft??

**Comment by phyzical** [comment]
feel free to just copy paste my changes i dont need credit :)

it should be fine the maintainer can take a while to get to prs

**Comment by phyzical** [comment]
👍 ill give it a test this afternoon

**Review by phyzical — APPROVED** [review]
looks good i just wonder if this actually fixes it though, rather i wonder why ffmpeg would cause the images to download correctly but the writer doesnt.

either way it achieves the same outcome so might aswell give it a try for a while 👍

**Comment by javalsai** [comment]
@phyzical It was probably that not all images were on the same format, and saving them as jpg caused weird things

**Comment by SwapnilSoni1999** [comment]
Just give a look to conflicts please 
Will merge afterwards
extremely sorry for being late 
My life is done nowdays 
Maybe will transfer my whole git to somebody 
I dont feel like doing anything

**Comment by javalsai** [comment]
> Will merge afterwards
> extremely sorry for being late

Don't worry about being late.

> Just give a look to conflicts please

They should be solved now

**Comment by SwapnilSoni1999** [comment]
awesome will publish by tomorrow

**Pull request merged**
