### PR TITLE
Fixes issue #96 where the folder name ends with a period('.')

### LINKED ISSUE #96: Error while trying to download song/album
Hello, I was trying to download some songs when suddenly, this error showed up
image

In order to counteract this, I tried creating another folder with the same name and restart the download. But it happened again, this time it's a metadata error. 
image
image

And apparently it only affects hololive songs and albums as I tried downloading an album and a single from another artist (TUYU) and it works just fine. Any reason why?
### Album - It's Raining After All
image
### Single - Loser Girl
image

Finally, when I try to access the folder, it gives a location unavailable error, very weird. There's no way I can delete this folder I have to use a third-party program to force delete it.
explorer_sNmjDfwl4u

Also another thing is that the album name is Bouquet but the folder is named after the first song in the album (Dreaming Days), but this doesn't happen to other album from other artist. Weird.
### hololive - Bouquet
image
### TUYU - It's Raining After All
image

I hope to receive an answer to this problem.

### PR DESCRIPTION
**Pull request by raprocks**
This fixes #96 by sanitizing the directory name and replacing the period with a empty string.

Other Minor patches:
* Make strings span multiline and wrap at 80 characters to abide by the limits
* Updated the package-lock.json with latest version.

### CODE REVIEW

**Comment by raprocks** [comment]
Also tested with the Issue Creator Provided link on Windows 10. Works Fine after the patch

**Comment by phyzical** [comment]
(haven't tested as i couldn't replicate the original issue either) 

But code wise looks good to me and looks like it what i thought it would have been 

GJ 👍

**Review by phyzical — APPROVED** [review]

**Comment by phyzical** [comment]
actually when i looks closer i think you could solve this by just updating the  `validateOutputSync` function to handle . also as the dir is joined in 
image

could you please try that first just to avoid extra code if we can :)

**Review by SwapnilSoni1999 — COMMENTED** [review]
I think `dir` doesnt needs to be validated because its pwd of the user

**Comment by SwapnilSoni1999** [comment]
Rest of the things looks fine <3 Great work 
Thanks alot. I'll merge after testing tomorrow

**Comment by raprocks** [comment]
actually `dir` is the pwd+the folder named after the artist. eg., pwd = "E:\", artist name = "x." then dir is `E:\x.\` so we need to validate the directory and hence the pr

**Pull request merged**
